name: Test physi
favicon: null
layout_spectrum: 0.019349202746525407
typography_spectrum: 0.7672898380551487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a52a4'
    - '#68cce6'
    - '#ffffff'
    - '#000000'
    - '#bce5f6'
  brandStrength: 0.6628161382395774
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
